#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App6.Resource", IsApplication=true)]

namespace App6
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int B_button = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int MeList_editText = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int Me_ERR_textView = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int Me_End = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int Me_Memo_editText = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int Me_button = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int Me_editText = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int S_button = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int YouList_editText = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int You_End = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int You_Memo_editText = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int You_button = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int You_editText = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int gridLayout1 = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout2 = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout3 = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
